### ISSUE TITLE
config.toml variables in commands?

### ISSUE THREAD

**Issue by alexxroche** [beac0n/ruroco#11]
In one of my test commands I tried to use `$config_dir` from the top of `/etc/ruroco/config.toml` as a variable in the command

```config.toml
config_dir = "/etc/ruroco/"

[commands]
reload = "mv $config_dir/config.toml ${config_dir}/config.arch ; cp $config_dir/backup_conf $config_dir/config.toml ; for c in ruroco-commander ruroco; do sudo systemctl restart $c; done"
```
Would this be dangerous or just require a pre-processor to do a substitution pass when loading config.toml ?

**Comment by beac0n** [comment]
See https://github.com/beac0n/ruroco/blob/b5210c1a6fd6b7179df7b042aa345df61014458a/src/commander.rs#L124

The commander module just runs the string a a simple command and adds one argument. It should be easy to set `config_dir` as additional argument, although I would then set it as `RUROROC_CONFIG_DIR` to stick the implicitly existing naming scheme of env vars.

We should also think of other env vars that would make sense to set that do not expose anything.

Regarding a pre-processor:

I would not like to add dependencies if not absolutely needed. TOML doesn't seem to have variables (see https://github.com/toml-lang/toml/issues/528) , so I would rather not like to change that default behavior by adding a pre-processor.

**Comment by beac0n** [comment]
I think a better way to solve this issue, is to just run a script here that has all the variables needed. So I think the following solution would be better:

```toml
config_dir = "/etc/ruroco/"

[commands]
reload = "/etc/ruroco/reload.sh"
```

`reload.sh` could look like this:

```bash
#!/usr/bin/env bash

# see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euxo pipefail

config_dir="/etc/ruroco/"

mv $config_dir/config.toml ${config_dir}/config.arch 
cp $config_dir/backup_conf $config_dir/config.toml 

sudo systemctl restart ruroco-commander
sudo systemctl restart ruroco
```
