### ISSUE TITLE
Replay against different Server possible?

### ISSUE THREAD

**Issue by RubenArtmann** [beac0n/ruroco#3]
looks to me like the packet does not identify the server and could be replayed against a different server (if the same private key is valid on more than one server)

https://github.com/beac0n/ruroco/blob/ce766751b51c8ff6246a2be02a0d028e8e880bcb/src/client.rs#L90-L113

just saw this on hackernews and this popped into my head while reading:
https://github.com/beac0n/ruroco?tab=readme-ov-file#security
```md
Each packet can only be sent once and will be blacklisted on the server.
```

**Comment by beac0n** [comment]
Hi @RubenArtmann. Thanks for the feedback. You are right, that could happen!

A solution would be to add the destination server to the encrypted data, and then let the server validate that.

Thanks for pointing it out! I will implement a fix :)

**Comment by beac0n** [comment]
fixed with https://github.com/beac0n/ruroco/pull/18
